# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_task.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(720, 804)
        Dialog.setStyleSheet("QDialog{\n"
"    border-radius: 24%;\n"
"    background: #2e2e2e\n"
"}")
        self.new_task_widget = QtWidgets.QWidget(Dialog)
        self.new_task_widget.setGeometry(QtCore.QRect(0, 0, 720, 804))
        self.new_task_widget.setStyleSheet("QWidget {\n"
"\n"
"    background : #2e2e2e;\n"
"}")
        self.new_task_widget.setObjectName("new_task_widget")
        self.new_task_title_label = QtWidgets.QLabel(self.new_task_widget)
        self.new_task_title_label.setGeometry(QtCore.QRect(30, 52, 616, 44))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.new_task_title_label.setFont(font)
        self.new_task_title_label.setStyleSheet("QLabel{\n"
"    color: #fff;\n"
"}")
        self.new_task_title_label.setObjectName("new_task_title_label")
        self.new_task_splite_line = QtWidgets.QLabel(self.new_task_widget)
        self.new_task_splite_line.setGeometry(QtCore.QRect(0, 109, 720, 1))
        self.new_task_splite_line.setStyleSheet("QLabel {\n"
"    background : #404040;\n"
"}")
        self.new_task_splite_line.setObjectName("new_task_splite_line")
        self.status_label = QtWidgets.QLabel(self.new_task_widget)
        self.status_label.setGeometry(QtCore.QRect(30, 126, 104, 24))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.status_label.setFont(font)
        self.status_label.setStyleSheet("QLabel{\n"
"    color: #fff;\n"
"}")
        self.status_label.setObjectName("status_label")
        self.start_task_label = QtWidgets.QLabel(self.new_task_widget)
        self.start_task_label.setGeometry(QtCore.QRect(183, 119, 104, 38))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.start_task_label.setFont(font)
        self.start_task_label.setStyleSheet("QLabel{\n"
"    background:#d68620;\n"
"    color: #fff;\n"
"    border-radius: 19px;\n"
"}")
        self.start_task_label.setAlignment(QtCore.Qt.AlignCenter)
        self.start_task_label.setObjectName("start_task_label")
        self.time_to_start_label = QtWidgets.QLabel(self.new_task_widget)
        self.time_to_start_label.setGeometry(QtCore.QRect(30, 170, 111, 24))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.time_to_start_label.setFont(font)
        self.time_to_start_label.setStyleSheet("QLabel{\n"
"    color: #fff;\n"
"}")
        self.time_to_start_label.setObjectName("time_to_start_label")
        self.repeat_task_label = QtWidgets.QLabel(self.new_task_widget)
        self.repeat_task_label.setGeometry(QtCore.QRect(30, 203, 104, 24))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.repeat_task_label.setFont(font)
        self.repeat_task_label.setStyleSheet("QLabel{\n"
"    color: #fff;\n"
"}")
        self.repeat_task_label.setObjectName("repeat_task_label")
        self.use_my_subtasks_label = QtWidgets.QLabel(self.new_task_widget)
        self.use_my_subtasks_label.setGeometry(QtCore.QRect(30, 240, 141, 24))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.use_my_subtasks_label.setFont(font)
        self.use_my_subtasks_label.setStyleSheet("QLabel{\n"
"    color: #fff;\n"
"}")
        self.use_my_subtasks_label.setObjectName("use_my_subtasks_label")
        self.hide_window_label = QtWidgets.QLabel(self.new_task_widget)
        self.hide_window_label.setGeometry(QtCore.QRect(30, 286, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.hide_window_label.setFont(font)
        self.hide_window_label.setStyleSheet("QLabel{\n"
"    color: #fff;\n"
"}")
        self.hide_window_label.setWordWrap(True)
        self.hide_window_label.setObjectName("hide_window_label")
        self.task_description_label = QtWidgets.QLabel(self.new_task_widget)
        self.task_description_label.setGeometry(QtCore.QRect(30, 349, 574, 24))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.task_description_label.setFont(font)
        self.task_description_label.setStyleSheet("QLabel{\n"
"    color: #fff;\n"
"}")
        self.task_description_label.setObjectName("task_description_label")
        self.task_description_widget = QtWidgets.QWidget(self.new_task_widget)
        self.task_description_widget.setGeometry(QtCore.QRect(30, 381, 656, 146))
        self.task_description_widget.setStyleSheet("QWidget{\n"
"    border-radius : 24%;\n"
"    background : #161616;\n"
"}")
        self.task_description_widget.setObjectName("task_description_widget")
        self.task_description = QtWidgets.QTextEdit(self.task_description_widget)
        self.task_description.setGeometry(QtCore.QRect(7, 12, 641, 120))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(12)
        self.task_description.setFont(font)
        self.task_description.setStyleSheet("QTextEdit{\n"
"    color: #fff;\n"
"}")
        self.task_description.setObjectName("task_description")
        self.task_description_label_2 = QtWidgets.QLabel(self.new_task_widget)
        self.task_description_label_2.setGeometry(QtCore.QRect(30, 541, 288, 24))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.task_description_label_2.setFont(font)
        self.task_description_label_2.setStyleSheet("QLabel{\n"
"    color: #fff;\n"
"}")
        self.task_description_label_2.setObjectName("task_description_label_2")
        self.time_to_start_label_2 = QtWidgets.QLabel(self.new_task_widget)
        self.time_to_start_label_2.setGeometry(QtCore.QRect(183, 170, 121, 24))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.time_to_start_label_2.setFont(font)
        self.time_to_start_label_2.setStyleSheet("QLabel{\n"
"    color: #fff;\n"
"}")
        self.time_to_start_label_2.setObjectName("time_to_start_label_2")
        self.comboBox = QtWidgets.QComboBox(self.new_task_widget)
        self.comboBox.setGeometry(QtCore.QRect(180, 201, 69, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox::down-arrow {\n"
"    image: url(:/assets/Icon chevron down.png);\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox{\n"
"    color: #c0c0c0;\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.subtasks_switch_checkbox = QtWidgets.QCheckBox(self.new_task_widget)
        self.subtasks_switch_checkbox.setGeometry(QtCore.QRect(186, 246, 40, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.subtasks_switch_checkbox.setFont(font)
        self.subtasks_switch_checkbox.setStyleSheet("/* Style for the QCheckBox */\n"
"QCheckBox::indicator {\n"
"    width : 40px;\n"
"    height : 20px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(:/assets/Switch1.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/assets/Switch 2.png);\n"
"    animation: toggleAnimation 0.5s ease-in-out;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    color : #fff;\n"
"}\n"
"\n"
"/* Keyframe animation for the toggle effect */\n"
"@keyframes toggleAnimation {\n"
"    0% {\n"
"        transform: scale(1);\n"
"    }\n"
"    50% {\n"
"        transform: scale(1.2);\n"
"    }\n"
"    100% {\n"
"        transform: scale(1);\n"
"    }\n"
"}")
        self.subtasks_switch_checkbox.setText("")
        self.subtasks_switch_checkbox.setObjectName("subtasks_switch_checkbox")
        self.hide_switch_checkbox = QtWidgets.QCheckBox(self.new_task_widget)
        self.hide_switch_checkbox.setGeometry(QtCore.QRect(186, 287, 40, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hide_switch_checkbox.setFont(font)
        self.hide_switch_checkbox.setStyleSheet("/* Style for the QCheckBox */\n"
"QCheckBox::indicator {\n"
"    width : 40px;\n"
"    height : 20px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(:/assets/Switch1.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/assets/Switch 2.png);\n"
"    animation: toggleAnimation 0.5s ease-in-out;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    color : #fff;\n"
"}\n"
"\n"
"/* Keyframe animation for the toggle effect */\n"
"@keyframes toggleAnimation {\n"
"    0% {\n"
"        transform: scale(1);\n"
"    }\n"
"    50% {\n"
"        transform: scale(1.2);\n"
"    }\n"
"    100% {\n"
"        transform: scale(1);\n"
"    }\n"
"}")
        self.hide_switch_checkbox.setText("")
        self.hide_switch_checkbox.setObjectName("hide_switch_checkbox")
        self.close_button = QtWidgets.QPushButton(self.new_task_widget)
        self.close_button.setGeometry(QtCore.QRect(674, 16, 24, 24))
        self.close_button.setStyleSheet("QPushButton {\n"
"    border : none;\n"
"    \n"
"    background-image: url(:/assets/Icon times.png);\n"
"}")
        self.close_button.setText("")
        self.close_button.setObjectName("close_button")
        self.trash_button = QtWidgets.QPushButton(self.new_task_widget)
        self.trash_button.setGeometry(QtCore.QRect(30, 14, 30, 24))
        self.trash_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-image: url(:/assets/Icon trash.png);\n"
"}")
        self.trash_button.setText("")
        self.trash_button.setObjectName("trash_button")
        self.pencil_button = QtWidgets.QPushButton(self.new_task_widget)
        self.pencil_button.setGeometry(QtCore.QRect(80, 16, 24, 24))
        self.pencil_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-image: url(:/assets/Icon pencil.png);\n"
"}")
        self.pencil_button.setText("")
        self.pencil_button.setObjectName("pencil_button")
        self.save_button = QtWidgets.QPushButton(self.new_task_widget)
        self.save_button.setGeometry(QtCore.QRect(650, 740, 31, 32))
        self.save_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-image: url(:/assets/Icon save.png);\n"
"}")
        self.save_button.setText("")
        self.save_button.setObjectName("save_button")
        self.calendar_button = QtWidgets.QPushButton(self.new_task_widget)
        self.calendar_button.setGeometry(QtCore.QRect(307, 171, 16, 17))
        self.calendar_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-image: url(:/assets/Icon calendar week.png);\n"
"}")
        self.calendar_button.setText("")
        self.calendar_button.setObjectName("calendar_button")
        self.listWidget = QtWidgets.QListWidget(self.new_task_widget)
        self.listWidget.setGeometry(QtCore.QRect(30, 580, 661, 141))
        self.listWidget.setStyleSheet("#listWidget{\n"
"    border-radius:20px;\n"
"    border:2px solid white\n"
"}")
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.new_task_title_label.setText(_translate("Dialog", "Create a New Task"))
        self.new_task_splite_line.setText(_translate("Dialog", "s"))
        self.status_label.setText(_translate("Dialog", "Status"))
        self.start_task_label.setText(_translate("Dialog", "Start Task"))
        self.time_to_start_label.setText(_translate("Dialog", "Time to start"))
        self.repeat_task_label.setText(_translate("Dialog", "Repeat task"))
        self.use_my_subtasks_label.setText(_translate("Dialog", "Use my subtasks"))
        self.hide_window_label.setText(_translate("Dialog", "Hide window from screenshots"))
        self.task_description_label.setText(_translate("Dialog", "Task Description"))
        self.task_description_label_2.setText(_translate("Dialog", "Subtasks"))
        self.time_to_start_label_2.setText(_translate("Dialog", "Select a Date"))
        self.comboBox.setItemText(0, _translate("Dialog", "Daily"))
        self.comboBox.setItemText(1, _translate("Dialog", "Week"))
        self.comboBox.setItemText(2, _translate("Dialog", "Month"))
        self.comboBox.setItemText(3, _translate("Dialog", "Year"))
        self.comboBox.setItemText(4, _translate("Dialog", "None"))
import resource_rc
